env:
  es2021: true
  node: true

extends:
  - 'airbnb-base'
  - 'airbnb-typescript/base'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
  project: './tsconfig.json'

plugins:
  - '@typescript-eslint'
  - 'unused-imports'

rules: {
  'import/prefer-default-export': 0,
  'class-methods-use-this': 0,
  '@typescript-eslint/no-unused-vars': 0,
  'unused-imports/no-unused-imports': 'error',
}
