export * from './cupom-unvailable';
export * from './user-already-get-coupom';
export * from './user-already-registered-in-form';
export * from './field-empty';
export * from './possible-errors';
export * from './accepted-terms-is-false';
export * from './user-not-registered-in-form';
export * from './invalid-email';
export * from './wrong-tennant-id';
